# Приложение A. Введение в PyTorch

## A.1. Что такое PyTorch

In [1]:
import torch

print(torch.__version__)

2.12.0+cpu


In [2]:
print(torch.cuda.is_available())

False


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/1.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/2.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/3.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/4.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/5.webp" width="800px">

 ---

 ## Упражнение A.1. Установка и настройка PyTorch

Документ [Советы по настройке Python](../../setup/01_optional-python-setup-preferences/README.md) в этом репозитории содержит дополнительные рекомендации и советы по настройке среды Python

---


## Упражнение A.2. Запуск кода

Документ [Установка библиотек, используемых в этой книге](../../setup/02_installing-python-libraries/README.md) и [директория](../../setup/02_installing-python-libraries/) содержат утилиты для проверки правильности настройки окружения

---

## A.2. Тензоры

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/6.webp" width="800px">

### A.2.1. Скаляры, векторы, матрицы и тензоры

In [3]:
import torch
import numpy as np

# создаём 0D тензор (скаляр) из целого числа Python
tensor0d = torch.tensor(1)

# создаём 1D тензор (вектор) из списка Python
tensor1d = torch.tensor([1, 2, 3])

# создаём 2D тензор из вложенного списка Python
tensor2d = torch.tensor([[1, 2], 
                         [3, 4]])

# создаём 3D тензор из вложенного списка Python
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], 
                           [[5, 6], [7, 8]]])

# создаём 3D тензор из массива NumPy
ary3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d)  # Копирует массив NumPy
tensor3d_3 = torch.from_numpy(ary3d)  # Делит память с массивом NumPy

In [4]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # остаётся неизменным

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [5]:
print(tensor3d_3) # изменяется из-за общего доступа к памяти

tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


### A.2.2. Типы тензорных данных

In [6]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [7]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


### A.2.3. Распространённые операции с тензорами в PyTorch

In [8]:
tensor2d = torch.tensor([[1, 2, 3], 
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
tensor2d.shape

torch.Size([2, 3])

In [10]:
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [13]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [14]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

 ---

Исходный тензор **2×3**:

```
[[1, 2, 3],
 [4, 5, 6]]
```

**tensor2d.T** (транспонирование, 3×2):
```
[[1, 4],
 [2, 5],
 [3, 6]]
```
С этим совпало.

---

**tensor2d.matmul(tensor2d.T)** — умножаем (2×3) на (3×2) → (2×2):
```
[1×1 + 2×2 + 3×3,  1×4 + 2×5 + 3×6]   = [14, 32]
[4×1 + 5×2 + 6×3,  4×4 + 5×5 + 6×6]   = [32, 77]
```

Результат:
```
[[14, 32],
 [32, 77]]
```

---

## A.3. Представление моделей в виде графов вычислений

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/7.webp" width="800px">

In [15]:
import torch.nn.functional as F

y = torch.tensor([1.0])  # истинная метка
x1 = torch.tensor([1.1]) # входной признак
w1 = torch.tensor([2.2]) # весовой параметр
b = torch.tensor([0.0])  # нейрон смещения

z = x1 * w1 + b          # чистый вход
a = torch.sigmoid(z)     # активация и выход

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


## A.4. Автоматическое дифференцирование упростилось

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/8.webp" width="800px">

In [16]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b 
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [17]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## A.5. Реализация многослойных нейронных сетей

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/9.webp" width="800px">

In [18]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
                
            # 1-й скрытый слой
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2-й скрытый слой
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # выходной слой
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [19]:
model = NeuralNetwork(50, 3)

In [20]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [21]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Общее количество обучаемых параметров модели:", num_params)

Общее количество обучаемых параметров модели: 2213


In [22]:
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0682, -0.0287,  0.0319,  ..., -0.0864,  0.1304,  0.1049],
        [-0.0349, -0.0206,  0.0611,  ..., -0.1386,  0.0790, -0.1275],
        [ 0.1168, -0.0175, -0.1191,  ..., -0.0199, -0.0217, -0.1247],
        ...,
        [ 0.0878, -0.0774,  0.1180,  ..., -0.0835, -0.0531,  0.1268],
        [-0.1388,  0.0226,  0.0194,  ..., -0.1169,  0.0485,  0.0858],
        [ 0.1243,  0.0727,  0.1153,  ...,  0.0721, -0.0263,  0.0114]],
       requires_grad=True)


In [23]:
torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [24]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [25]:
torch.manual_seed(123)

X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [26]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [27]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6. Настройка эффективных загрузчиков данных

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/10.webp" width="800px">

In [28]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])

In [29]:
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [30]:
from torch.utils.data import Dataset


class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]        
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [31]:
len(train_ds)

5

In [32]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)

In [33]:
test_ds = ToyDataset(X_test, y_test)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [34]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Пакет {idx+1}:", x, y)

Пакет 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Пакет 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Пакет 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [35]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [36]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Пакет {idx+1}:", x, y)

Пакет 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Пакет 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/11.webp" width="800px">

## A.7. Типичный цикл обучения

In [37]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)
        
        loss = F.cross_entropy(logits, labels) # Функция потерь
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
        ### ЛОГГИРОВАНИЕ
        print(f"Эпоха: {epoch+1:03d}/{num_epochs:03d}"
              f" | Пакет {batch_idx+1:03d}/{len(train_loader):03d}"
              f" | Потери на обучении/валидации: {loss:.2f}")

    model.eval()
    # Опциональная оценка модели

Эпоха: 001/003 | Пакет 001/002 | Потери на обучении/валидации: 0.75
Эпоха: 001/003 | Пакет 002/002 | Потери на обучении/валидации: 0.65
Эпоха: 002/003 | Пакет 001/002 | Потери на обучении/валидации: 0.44
Эпоха: 002/003 | Пакет 002/002 | Потери на обучении/валидации: 0.13
Эпоха: 003/003 | Пакет 001/002 | Потери на обучении/валидации: 0.03
Эпоха: 003/003 | Пакет 002/002 | Потери на обучении/валидации: 0.00


 ---

 ## Упражнение A.3. Определение параметров нейронной сети

In [38]:
import torch

class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
                
            # 1-й скрытый слой
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2-й скрытый слой
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # выходной слой
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [39]:
model = NeuralNetwork(2, 2)

num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Общее количество обучаемых параметров модели:", num_params)

Общее количество обучаемых параметров модели: 752


 ---

In [40]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs)

tensor([[ 0.1506, -0.5124],
        [ 0.1235, -0.4883],
        [ 0.0887, -0.4726],
        [-0.3355, -0.3464],
        [-0.3871, -0.3835]])


In [41]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([[0.6599, 0.3401],
        [0.6483, 0.3517],
        [0.6368, 0.3632],
        [0.5027, 0.4973],
        [0.4991, 0.5009]])
tensor([0, 0, 0, 0, 1])


In [42]:
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 0, 1])


In [43]:
predictions == y_train

tensor([ True,  True,  True, False,  True])

In [44]:
torch.sum(predictions == y_train)

tensor(4)

In [45]:
def compute_accuracy(model, dataloader):

    model.eval()
    correct = 0.0
    total_examples = 0
    
    for idx, (features, labels) in enumerate(dataloader):
        
        with torch.no_grad():
            logits = model(features)
        
        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()

In [46]:
compute_accuracy(model, train_loader)

0.75

In [47]:
compute_accuracy(model, test_loader)

0.5

## A.8. Сохранение и загрузка моделей

In [48]:
torch.save(model.state_dict(), "model.pth")

In [49]:
model = NeuralNetwork(2, 2) # должна в точности совпадать с исходной моделью
model.load_state_dict(torch.load("model.pth", weights_only=True))

<All keys matched successfully>