# Приложение A. Введение в PyTorch

## A.1. Что такое PyTorch

In [1]:
import torch

print(torch.__version__)

2.12.0+cpu


In [2]:
print(torch.cuda.is_available())

False


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/1.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/2.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/3.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/4.webp" width="800px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/5.webp" width="800px">

 ---

 ## Упражнение A.1. Установка и настройка PyTorch

Документ [Советы по настройке Python](../../setup/01_optional-python-setup-preferences/README.md) в этом репозитории содержит дополнительные рекомендации и советы по настройке среды Python

---


## Упражнение A.2. Запуск кода

Документ [Установка библиотек, используемых в этой книге](../../setup/02_installing-python-libraries/README.md) и [директория](../../setup/02_installing-python-libraries/) содержат утилиты для проверки правильности настройки окружения

---

## A.2. Тензоры

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/6.webp" width="800px">

### A.2.1. Скаляры, векторы, матрицы и тензоры

In [3]:
import torch
import numpy as np

# создаём 0D тензор (скаляр) из целого числа Python
tensor0d = torch.tensor(1)

# создаём 1D тензор (вектор) из списка Python
tensor1d = torch.tensor([1, 2, 3])

# создаём 2D тензор из вложенного списка Python
tensor2d = torch.tensor([[1, 2], 
                         [3, 4]])

# создаём 3D тензор из вложенного списка Python
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], 
                           [[5, 6], [7, 8]]])

# создаём 3D тензор из массива NumPy
ary3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d)  # Копирует массив NumPy
tensor3d_3 = torch.from_numpy(ary3d)  # Делит память с массивом NumPy

In [4]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # остаётся неизменным

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [5]:
print(tensor3d_3) # изменяется из-за общего доступа к памяти

tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


### A.2.2. Типы тензорных данных

In [6]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [7]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


### A.2.3. Распространённые операции с тензорами в PyTorch

In [8]:
tensor2d = torch.tensor([[1, 2, 3], 
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
tensor2d.shape

torch.Size([2, 3])

In [10]:
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [13]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [14]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

 ---

Исходный тензор **2×3**:

```
[[1, 2, 3],
 [4, 5, 6]]
```

**tensor2d.T** (транспонирование, 3×2):
```
[[1, 4],
 [2, 5],
 [3, 6]]
```
С этим совпало.

---

**tensor2d.matmul(tensor2d.T)** — умножаем (2×3) на (3×2) → (2×2):
```
[1×1 + 2×2 + 3×3,  1×4 + 2×5 + 3×6]   = [14, 32]
[4×1 + 5×2 + 6×3,  4×4 + 5×5 + 6×6]   = [32, 77]
```

Результат:
```
[[14, 32],
 [32, 77]]
```

---